services:
  panel:
    image: pterodactyl
    build: ./docker
    ports:
      - 8080:8080
    environment:
      - TZ=UTC

  wings:
    image: pterodactyl-wings
    build: ./docker/wings
    ports:
      - 8081:8080
    environment:
      - TZ=UTC
    command: wings --debug

  mariadb:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: "sdfghjkl"
      MARIADB_USER: "pterodactyl"
      MARIADB_PASSWORD: "pterodactyl"
      MARIADB_DATABASE: "panel"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis

volumes:
  db-data:
